import { StyleSheet } from "react-native";

export default StyleSheet.create({
    Cardcontainer:{
    marginLeft:0,
    marginRight:0,
    marginTop:0,
    marginBottom:0,
    backgroundColor:'#14717c',
    borderTopWidth:0,
    height:200,
    justifyContent:'flex-end'
    },
    Headgreet:{
        fontSize:30,
        color:'#fff',
        fontWeight:'500'
    },
    date:{
        fontSize:15,
        color:'#CAD5E2',
        marginTop:10
    },
    medication:{
        marginVertical:20,
        marginHorizontal:20
    },
    medicationtitle:{
        fontSize:16,
        color:'#000',
        fontWeight:'700'
    },
    mediList:{
        width:250,
        marginLeft:20,
    marginRight:0,
    marginTop:0,
    marginBottom:0,
    borderRadius:10,
    paddingLeft:0,
    paddingRight:0,
    paddingTop:0
    },
    datefield:{
        width:'100%',
        
        backgroundColor:'#fbbab2',
        borderTopLeftRadius:10,
        borderTopRightRadius:10,
        paddingHorizontal:20,
        paddingVertical:10
    },
    datefieldtitle:{
        fontSize:30,
        color:'#fff',
        fontWeight:'900'
    },
    value:{
        fontSize:18,
        color:'#fff',
        fontWeight:'500'
    },
    appointment:{
    marginRight:25,
    marginTop:0,
    marginLeft:25,
    marginBottom:0,
    borderRadius:10,
    paddingTop:10
    }
})